// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmtKWbmIcGqSPLhxScE-x4LtTcNQXrY8',
    appId: '1:697021615063:web:9b30dff6cf10bfeff91992',
    messagingSenderId: '697021615063',
    projectId: 'test-f2195',
    authDomain: 'test-f2195.firebaseapp.com',
    storageBucket: 'test-f2195.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVLCVN1_WRc81PsOWyr3mKOty3fq8x1ew',
    appId: '1:697021615063:android:09a05cfe0c0de8acf91992',
    messagingSenderId: '697021615063',
    projectId: 'test-f2195',
    storageBucket: 'test-f2195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARompbm5ORmhpBtwy-BqYUQi-g8yhQaHM',
    appId: '1:697021615063:ios:55f1b440d83b549ef91992',
    messagingSenderId: '697021615063',
    projectId: 'test-f2195',
    storageBucket: 'test-f2195.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARompbm5ORmhpBtwy-BqYUQi-g8yhQaHM',
    appId: '1:697021615063:ios:55f1b440d83b549ef91992',
    messagingSenderId: '697021615063',
    projectId: 'test-f2195',
    storageBucket: 'test-f2195.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );
}